export const auditTypes = ['SOC 1', 'SOC 2', 'SOX', 'PCI-DSS', 'HIPAA', 'GDPR', 'FedRAMP', 'ISO 27001'];

export const scopeOptions = {
  'SOC 2': [
    'Security',
    'Availability', 
    'Processing Integrity',
    'Confidentiality',
    'Privacy'
  ],
  'ISO 27001': [
    'AI-A05-1-1 Social Media Policy',
    'AI-A05-1-2 HR Security Policy',
    'AI-A05-4-1 Information Security Whistleblowing Policy',
    'AI-A05-7-1 Threat Intelligence Policy',
    'AI-A05-10-1 Acceptable Use Policy',
    'AI-A05-15-1 Access Control Policy',
    'AI-A05-23-1 Cloud Services Policy',
    'AI-A05-10-2 Internet Access Policy',
    'AI-A05-9-1 Asset Management Policy',
    'AI-A05-10-6 Online Collaboration Policy',
    'AI-A05-10-3 Electronic Messaging Policy',
    'AI-A05-32-1 IP and Copyright Compliance Policy',
    'AI-A05-33-1 Records Retention and Protection Policy',
    'AI-A05-34-1 Privacy & data protection policy',
    'APL-A06-7-1 Remote Working Policy',
    'APL-A07-1-1 Physical Security Policy',
    'APL-A07-4-1 CCTV Policy',
    'APL-A07-7-1 Clear Desk and Clear Screen Policy',
    'APL-A08-1-1 Mobile Device Policy',
    'APL-A08-1-2 BYOD Policy',
    'APL-A08-3-1 Dynamic Access Control Policy',
    'APL-A08-7-1 Anti-Malware Policy',
    'APL-A08-8-1 Technical Vulnerability Management Policy',
    'APL-A08-9-1 Configuration Management Policy',
    'APL-A08-10-1 Information Deletion Policy',
    'APL-A08-11-1 Data Masking Policy',
    'APL-A08-12-1 Data Leakage Prevention Policy',
    'APL-A08-13-1 Backup Policy',
    'APL-A08-14-1 Availability Management Policy',
    'APL-A08-15-1 Logging and Monitoring Policy',
    'APL-A08-16-1 Monitoring Policy',
    'APL-A08-19-1 Software Policy',
    'APL-A08-20-1 Network Security Policy',
    'APL-A08-23-1 Web Filtering Policy',
    'APL-A08-24-1 Cryptographic Policy',
    'APL-A08-25-1 Secure Development Policy',
    'APL-A08-28-1 Secure Coding Policy'
  ]
};